spring:
  profiles:
    active:
      dev
    group:
      local-env:
        - local
      dev-env:
        - dev
      prod-env:
        - prod
    include:
      - oauth
      - crawler
      - s3

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true